### ISSUE TITLE
Please upload US version

### ISSUE THREAD

**Issue by ahmaddanyal06** [yschroeder/face-shield#15]
Hi, I've been using your version without the text. I just realized that these are the EU/International version. Can you please modify the US version and upload that as well? 

Thank you!!

**Comment by yschroeder** [comment]
I look into it. Sorry my time is very limited at the moment (I am a father since 6 days).

**Comment by yschroeder** [comment]
US version of the original RC3 is now available: 56ddc267c4479020bed70c6024ddb9ea6280f21f

**Comment by ahmaddanyal06** [comment]
Thank you so much!
