### ISSUE TITLE
888 version

### ISSUE THREAD

**Issue by thoka** [yschroeder/face-shield#5]
Could you provide a version with standard 80-80-80 distance between the holders? 
This would enable easy punching of a4 sheets with a common double-puncher.

For simple shields a total height of 11mm seems to be enough. 
So this could be a fast to print lightweight design.

**Comment by yschroeder** [comment]
There are already 888 versions avaialable as remix of the original one AFAIK. I might try to create my optimized version as 888, but I won't find the time today...

**Comment by yschroeder** [comment]
We decided to not make an 888 version. The reasons can be found in the FAQ of the README.
