### ISSUE TITLE
Stapel STL fehlerhaft

### ISSUE THREAD

**Issue by joerg900** [yschroeder/face-shield#8]
Simplify3d, Cura laden die Stapel-STLs nicht, aufgrund eines Fehlers in der Datei.

| Slicer |                        Fehlermeldung                        |
|--------|-------------------------------------------------------------|
| S3D    | Error importing STL file. incorrect binary format detected. |
| Cura   | Invalid File                                                |
                                             |

**Comment by vBJohannes** [comment]
Welcher der Stapel-Dateien? Ist das eventuell mit dem Fix aus #6 bereits behoben?

**Comment by joerg900** [comment]
Bei allen Dateien, habe den aktuellsten Stand vor Erstellung des Issues geladen. Laut Commit-Kommentar war das nach dem Fix aus #6.

**Comment by vBJohannes** [comment]
S3D kann ich nicht testen. Mit UltimakerCura4.5.0 lassen sich alle Stacks per Drag-and-Drop importieren und slicen. Slicing dauert zwar lange, aber ich bekomme bei keinem Stapel Fehler.
Hier beispielhaft der 7er Stapel.
![grafik](https://user-images.githubusercontent.com/9631621/78146666-c0cbf400-7432-11ea-9966-892192077cfe.png)

**Comment by joerg900** [comment]
Der Fehler lag bei mir. "Rechtsklick-->Ziel speicher unter..." führt nicht wie erwartet zum Download des Modells, sondern zu einer .STL-Datei, die den HTML Inhalt der Seite beinhaltet.
